services:
  rocketmq-client:
    build: .
    container_name: rmq-client-container
    environment:
      - TZ=Europe/Berlin
      - RMQ_ENDPOINT=${RMQ_ENDPOINT}
      - RMQ_TOPIC=${RMQ_TOPIC}
      - RMQ_GROUP=${RMQ_GROUP}
      - RMQ_ACCESS_KEY=${RMQ_ACCESS_KEY}
      - RMQ_SECRET_KEY=${RMQ_SECRET_KEY}
      - MQTT_URL=${MQTT_URL}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASS=${MQTT_PASS}