name: "RocketMQ to MQTT Bridge"
description: "Bridges messages between RocketMQ 4.0 and a local MQTT broker."
version: "1.0.0"
slug: "rocket_mq_2_mqtt"
arch:
  - aarch64
  - amd64
  - armv7
init: false
options:
  RMQ_ENDPOINT: "broker.example.com:9876"
  RMQ_TOPIC: "112456789012345678901ab2"
  RMQ_GROUP: "112456789012345678901ab2"
  RMQ_ACCESS_KEY: "K.XXXXXXXXXXXXXXXXXXXXXXX"
  RMQ_SECRET_KEY: "XXXXXXXXXXXXXXXXXXXXXXX"
  MQTT_URL: "tcp://x.x.x.x:1883"
  MQTT_USER: "username"
  MQTT_PASS: "password"
schema:
  RMQ_ENDPOINT: str
  RMQ_TOPIC: str
  RMQ_GROUP: str
  RMQ_ACCESS_KEY: str
  RMQ_SECRET_KEY: str
  MQTT_URL: str
  MQTT_USER: str?
  MQTT_PASS: str?